name: Run Parser

on: 
  push:
    branches: [main]  

jobs:
  run-parser-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run parser with input
      run: ./bin/parser bin/test.txt
